In [1]:
import numpy as np
v=np.array([4])
print("vector: ",v )

vector:  [4]


In [5]:
import numpy as np
v=np.array([3,4])
print("vector: ",v.shape) # one dimensional array with 2 elements


vector:  (2,)


In [7]:
M=np.array([[1,2],[3,4],[5,6]])

In [9]:
M

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
M.shape

(3, 2)

In [21]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
res1=a+b
res2=a-b
print(res1)
print(res2)

[5 7 9]
[-3 -3 -3]


In [29]:
import numpy as np
v=np.array([4])
print(v.shape)

(1,)
